<a href="https://colab.research.google.com/github/AlxeverCodeX/git-github/blob/master/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1UJBYPtRdyxaSTABPurB0Cd8mAV04t5x2')

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


Assignment 2 - Numpy Array Operations

All about Numpy array operations


Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [62]:
!pip install jovian --upgrade -q

In [63]:
import jovian

In [64]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/salberthp89/numpy-array-operations


'https://jovian.ml/salberthp89/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [65]:
import numpy as np

In [66]:
# List of functions explained 
function1 = np.arange
function2 = np.zeros
function3 = np.eye
function4 = np.add
function5 = np.array

## Function 1 - np.arange

Returns an array with evenly spaced numbers. 

In [67]:
# Example 1 
arr = np.arange(1,10)
print(arr)



[1 2 3 4 5 6 7 8 9]


The above exampe shows hat thr numpy arange function prints elements in a list in the specified range which is start and stop

In [68]:

# Example 2 - working
arr2=np.arange(start=1,stop=50,step=5)
print(arr2)

[ 1  6 11 16 21 26 31 36 41 46]


the above example shows us the use of a step count. The step argument tells the function to print the next element by adding start val with step value

In [69]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.arange(5,10.7,0.1)

print(arr3)

[ 5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3
  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7
  7.8  7.9  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1
  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5
 10.6]



np.arange function might give ius results that are no consistent with floating point numbers better to use linespace in such cases

The above functions is used when you want a sequence of numbers

In [70]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/salberthp89/numpy-array-operations


'https://jovian.ml/salberthp89/numpy-array-operations'

## Function 2 - np.zeros

To generate an array ofall zeros

In [71]:
# Example 1 - working
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


the above examples shows that the function takes in an integer and prints out a list of pure zeros

In [72]:
# Example 2 - working
arr1 = np.zeros((5,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


the above example shows that we pass in a tuple of numbers to specify dimensions

In [73]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = np.zeros(5,5)
print(arr2)

TypeError: ignored

this error is a a result of not putting the right amount of brackets so we add double brackets when imputing a tuple

It works best when creating a pure array of zeros

In [74]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/salberthp89/numpy-array-operations


'https://jovian.ml/salberthp89/numpy-array-operations'

## Function 3 - np.eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [75]:
# Example 1 - working
ar = np.eye(10)
print(ar)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


when you pass in an argument it prints a 2 dimensional array of ones and zeros

In [76]:
# Example 2 - working

b = np.eye(2, dtype = float) 
print("Matrix b : \n", b)

Matrix b : 
 [[1. 0.]
 [0. 1.]]


# 2x2 matrix with 1's on main diagnol 

In [77]:
# Example 3 - breaking (to illustrate when it breaks)
g = np.eye(2,20.3)
print(g)

TypeError: ignored

it show that passing in a float as an argument cant work so u use it without it

Some closing comments about when to use this function.

In [78]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/salberthp89/numpy-array-operations


'https://jovian.ml/salberthp89/numpy-array-operations'

## Function 4- np.add

it is used when we want to add two matrix

In [79]:
# Example 1 - working
arr1=np.arange(1,10)
print(arr1)

arr2=np.arange(4,46,5)
print( arr2)

result_arr=np.add(arr1,arr2)
print( result_arr)

[1 2 3 4 5 6 7 8 9]
[ 4  9 14 19 24 29 34 39 44]
[ 5 11 17 23 29 35 41 47 53]


The above example illustrates the  addition of two matrix.


In [80]:
# Example 2 - working
arr1=np.arange(1,10).reshape(3,3)
print(arr1)

arr2=np.arange(5,16,5).reshape(1,3)
print( arr2)

result_arr=np.add(arr1,arr2)
print( result_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5 10 15]]
[[ 6 12 18]
 [ 9 15 21]
 [12 18 24]]


The above example illustrates use of broadcasting principle used in np.add function.Here arr2 is of size (1,3) and arr1 is of size (3,3) so to make arr2 of size (3,3) first row is repeated three times to create (3,3) matrix and then addition happens.

In [81]:
# Example 3 - breaking (to illustrate when it breaks)
arr1=np.arange(1,10)
print(arr1)

arr2=np.arange(5,16,5)
print( arr2)

result_arr=np.add(arr1,arr2)
print( result_arr)

[1 2 3 4 5 6 7 8 9]
[ 5 10 15]


ValueError: ignored

we have to reshape it to make it work unless it wont broadcast well

we use np.add() function  when we want to compute the addition of two array. It add arguments element-wise

In [82]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/salberthp89/numpy-array-operations


'https://jovian.ml/salberthp89/numpy-array-operations'

## Function 5 - np.array

used to create arrays


In [83]:
# Example 1 - working
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


it shows a 1-D array containing the values 1,2,3,4,5

In [84]:
# Example 2 - working
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


it shows the use of  a tuple to create a NumPy array

In [85]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: ignored

it shows that we need to reshape the arraysaccording to the size of the array else it will result into an error

this function is very useful especially for beginners who want to test out codes because it makes creating and manipulating array seamless

In [86]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/salberthp89/numpy-array-operations


'https://jovian.ml/salberthp89/numpy-array-operations'

## Conclusion
We have demonstrated 5 common functions used used in numpy array  operations. Numpy array operations provides faster computing than python lists and other functions like mean,median,max,min are used in data analysis. Function like add find more use in deep learning and neural networks and the whole numpy module becomes a ground for further pandas understanding and operations.



## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
*Tutorial Point : https://www.tutorialspoint.com/numpy/index.htm

In [87]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/salberthp89/numpy-array-operations


'https://jovian.ml/salberthp89/numpy-array-operations'