<a href="https://colab.research.google.com/github/AlxeverCodeX/git-github/blob/master/Tensor_Functions_Jovian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1Lj-DdsmBZhZrp-Z3jQ8vYs5a2B4nFGKn')

# Pytorch Fuctions

PyTorch is a Machine Learning library with increasing popularity.Pytorch is an open source machine learning framework that accelerates the path from research prototyping to production deployment. we will explore five functions available in PyTorch. 
- torch.rand()
- torch.mean()
- torch.linspace()
- torch.Tensor.filldiagonal()
-torch.view(shape)

Before we begin, let's install and import PyTorch

In [37]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [38]:
# Import torch and other required modules
import torch

## torch.rand()
This function returns a tensor filled with random numbers from a uniform distribution on the interval [0,1). Some of its parameters are listed below:
size (int) — a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.
dtype (torch.dtype, optional) — the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).
requires_grad (bool, optional) — If autograd should record operations on the returned tensor. Default: False.

In [39]:
# Example 1 - working (change this)
torch.rand(9)

tensor([0.0584, 0.0304, 0.4461, 0.3461, 0.5811, 0.8035, 0.0288, 0.2315, 0.0577])

we got a tensor vector of 9 elements in the interval [0,1).

In [40]:
# Example 2 - working
torch.rand(3,4)

tensor([[0.0837, 0.8230, 0.7204, 0.8742],
        [0.8559, 0.3983, 0.7658, 0.9214],
        [0.7901, 0.2214, 0.3789, 0.1738]])

we get a tensor of shape 3x4 with elements in the interval [0,1)

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
tens3=torch.tensor([[1, 2], [3, 4, 5]])
print(tens3)

ValueError: ignored

The function breaks when an element is added to the tensor that does not satisfy the dimensions of the tensor/matrix.

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [42]:
!pip install jovian --upgrade --quiet

In [43]:
import jovian

In [44]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/salberthp89/01-tensor-operations


'https://jovian.ai/salberthp89/01-tensor-operations'

## torch.mean()

A  torch.mean function returns the mean or average of your tensor. Some of its parameters are listed below.
input (Tensor) — the input tensor.
dim (int or tuple of python:ints) — the dimension or dimensions to reduce.
keepdim (bool) — whether the output tensor has dim retained or not.
out (Tensor, optional) — the output tensor.

In [48]:
# Example 1 - working
random_tensor = torch.randn((5,3)) #creating a tensor of size 5x3 with randn function
print(random_tensor)
torch.mean(random_tensor)

tensor([[ 0.0540,  0.8718,  0.3673],
        [ 1.0008, -0.1043,  0.9659],
        [ 0.1389,  0.8262, -0.4942],
        [ 0.4942, -1.9824, -0.3379],
        [-0.3733,  0.8127, -0.7720]])


tensor(0.0978)

In the cell, by the application of torch.mean() on the tensor vector, we can observe that all the numbers in the tensor vector are added and divided by the number of elements.


In [49]:
 #Example 2 - working
random_tensor = torch.randn((3,5)) #creating a tensor of size 3x5 with randn function
print(random_tensor)
#dim=1 for rows and dim=0 for columns
print("\n dim paramater applied over rows    : ",torch.mean(random_tensor,dim=0)) 
print("\n dim paramater applied over columns : ",torch.mean(random_tensor,dim=1)) 

tensor([[-0.1497, -0.7362,  0.0538,  0.5317, -0.5685],
        [-0.5917, -0.4925, -0.2814,  1.4961, -0.5621],
        [-1.0043, -1.0576, -0.1995,  1.0184,  0.4052]])

 dim paramater applied over rows    :  tensor([-0.5819, -0.7621, -0.1424,  1.0154, -0.2418])

 dim paramater applied over columns :  tensor([-0.1738, -0.0863, -0.1675])


the torch.mean() is applied over a (3,5) tensor with an additional parameter called ‘dim’.This parameter specifies that the average should be taken over rows(for each column, if dim=0) or over columns(for each row, if dim=1)

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
bool_tensor = torch.tensor([1,0,1]*2,dtype=torch.bool)
print(bool_tensor)
torch.mean(bool_tensor)

tensor([ True, False,  True,  True, False,  True])


RuntimeError: ignored

 we get the run-time error “Can only calculate the mean of floating types. Got Bool instead.” This means that torch.mean() can only be applied on floating types and rest all other cases fail.

his function can be used when someone wants to calculate the average of a tensor like when we want to use Root Mean Squared Error (RMSE) as loss function.


In [51]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/salberthp89/01-tensor-operations


'https://jovian.ai/salberthp89/01-tensor-operations'

## torch.linspace()

This is used to create a 1D equally spaced tensor between the values start and end . We can specify the size of the tensor with the steps parameters. The default is steps=100

In [52]:
# Example 1 - working
torch.linspace(-10,4,25)


tensor([-10.0000,  -9.4167,  -8.8333,  -8.2500,  -7.6667,  -7.0833,  -6.5000,
         -5.9167,  -5.3333,  -4.7500,  -4.1667,  -3.5833,  -3.0000,  -2.4167,
         -1.8333,  -1.2500,  -0.6667,  -0.0833,   0.5000,   1.0833,   1.6667,
          2.2500,   2.8333,   3.4167,   4.0000])

we see, the start=10,end=4 and steps=25. So, we get 25 equally spaced points between 10 and 4 (both inclusive). By default, PyTorch gives us the elements as floating points.

In [53]:
# Example 2 - working
torch.linspace(-10,4,25,dtype=torch.int)

tensor([-10,  -9,  -8,  -8,  -7,  -7,  -6,  -5,  -5,  -4,  -3,  -3,  -2,  -2,
         -1,   0,   0,   0,   0,   1,   1,   2,   2,   3,   4],
       dtype=torch.int32)

we are getting the elements that are of type int32.

In [54]:
# Example 3 - breaking (to illustrate when it breaks)
tensor_ones = torch.ones((1,13))
print("Tensor with ones: ",tensor_ones)
print("Our Linspace tensor: ",torch.linspace(-11,7,13,out=tensor_ones,dtype=torch.int32))
tensor_ones

Tensor with ones:  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


RuntimeError: ignored

The “out” parameter of torch.linspace() which specifies the desired tensor to be replaced by the values returned from the torch.linspace function. The run-time error “dtype Int does not match dtype of out parameter (Float)” tells us that both the types of tensors should be the same to use the “out” parameter.

orch.linspace can be used to create data in the form of tensors, when we know that the real data lies in particular interval.

In [55]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/salberthp89/01-tensor-operations


'https://jovian.ai/salberthp89/01-tensor-operations'

## torch.Tensor.filldiagonal()

This function is used to fill the diagonals of the the tensor with a particular value.

In [56]:
# Example 1 - working
tens1=torch.zeros(3, 3)
print(tens1)
tens1.fill_diagonal_(1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

This function fills in the value specified as its argument(i.e. 1) as the diagonal value of the tensor(tens1).

In [57]:
# Example 2 - working
torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]]).fill_diagonal_(0)


tensor([[0, 2, 3],
        [4, 0, 6],
        [7, 8, 0]])

function can be directly applied on the tensor or by using a variable as in previous example.

In [58]:
# Example 3 - breaking (to illustrate when it breaks)
tens2=torch.tensor([[[1, 2, 3, 4]],[[5, 6, 7, 8]]])
print(tens2)
tens2.size()
tens2.fill_diagonal_(10)

tensor([[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]])


RuntimeError: ignored

The matrix dimension does not satisfy the condition of the diagonal matrix to be imposed with a value.

This function can be used at any relevant place where a particular diagonal value is to be imposed in the tensor.

In [59]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/salberthp89/01-tensor-operations


'https://jovian.ai/salberthp89/01-tensor-operations'

## torch.view(shape)

View tensor shares the same underlying data with its base tensor. View avoids explicit data copy, thus allows us to do fast and memory-efficient reshaping, slicing, and element-wise operations.

In [60]:
# Example 1 - working
random_tensor = torch.arange(1., 17.)
print(random_tensor)
random_tensor.view(8,2)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])


tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.],
        [13., 14.],
        [15., 16.]])

we get a copy of the given tensor in a different size on which we can perform operations.

In [61]:
# Example 2 - working
x = torch.randn(4, 4)
print(x.size())
y = x.view(16)
print(y.size())
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
z.size()

torch.Size([4, 4])
torch.Size([16])


torch.Size([2, 8])

This is another example of using the view function. Here, the -1 is inferred from other dimensions.

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
random_tensor = torch.randint(100,size=(10,6))
print(random_tensor)
random_tensor.view(8,2)

tensor([[62, 96, 20, 66, 91, 47],
        [69, 81, 95, 71, 35, 47],
        [32, 65, 24, 44, 54, 26],
        [92, 29, 96, 37, 94, 76],
        [70, 81, 40, 57, 91, 48],
        [84, 86, 42, 42, 50, 37],
        [33, 64, 34, 68, 26, 91],
        [90, 15, 89, 69, 51, 79],
        [81, 16, 60, 65, 96, 37],
        [58, 89, 44, 88, 22, 44]])


RuntimeError: ignored

Here, we get an error because the shape should match the size of the input tensor.

orch.reshape() function would return a view and is exactly the same as using torch.Tensor.view() as long as the new shape is compatible with the shape of the original tensor. Otherwise, it will return a copy.

In [63]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/salberthp89/01-tensor-operations


'https://jovian.ai/salberthp89/01-tensor-operations'

## Conclusion

i have covered 5 interestuing functions in pytorch .You can refer to the official documentation for the complete list of available functions.
https://pytorch.org/docs/stable/index.html

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [64]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/salberthp89/01-tensor-operations


'https://jovian.ai/salberthp89/01-tensor-operations'